CREATE TABLE MATCHS (
	MATCH_ID VARCHAR(20) CONSTRAINT PK_MATCH_ID PRIMARY KEY,
	FINALLV NUMERIC(9) NOT NULL,
	PLACEMENT NUMERIC(9) NOT NULL,
	PLAYERS_ELIMINATED NUMERIC(9) NOT NULL,
	LASTROUND NUMERIC(9) NOT NULL,
	PLAYERS_DAMAGE NUMERIC(9) NOT NULL
);

CREATE TABLE TRAITS (
	MATCH_ID VARCHAR(20) CONSTRAINT PK_MATCHID_TRAIT PRIMARY KEY,
	TRAIT_NAME VARCHAR(20),
	NUM_UNITS NUMERIC(9),
	TRAIT_STYLE NUMERIC(9),
	TIER_CURRENT NUMERIC(9),
	TIER_TOTAL NUMERIC(9),
	FOREIGN KEY (MATCH_ID) REFERENCES MATCHS ON DELETE CASCADE
);

CREATE TABLE MATCH_PLAYERS (
	MATCH_ID VARCHAR(20) NOT NULL CONSTRAINT PK_PLAYER_MATCHID PRIMARY KEY,
	PUUID VARCHAR(100),
	PLAYER_NAME VARCHAR(20),
	FOREIGN KEY (MATCH_ID) REFERENCES MATCHS ON DELETE CASCADE
)